#ddev-generated
web_environment:
  - DRUSH_OPTIONS_URI=${DDEV_PRIMARY_URL}

hooks:
  post-start:
    - composer: global config --no-plugins allow-plugins.dpp/composer-plugin true
    - composer: global require -n dpp/composer-plugin:^1@beta